# Trivy-operator application configuration
app:
  name: trivy-operator
  namespace: trivy-system
  cluster: apps
  project: apps-platform

  source:
    path: argocd/applications/platform/trivy-operator/charts
    helm:
      releaseName: trivy-operator
      valueFiles:
        - ../config/values.yaml

  destination:
    server: https://192.168.178.139:6443

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m

