---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: external-dns
spec:
  encryptedData:
    api-token: AgCiHM8FXzLzn7Q5eM04gpox8YgaTFan4gUKT7rTBkitqW8p0KfcAXfx8AduRCvQA75Mv6SHRCrmztR0MT2DijgTQPP0cI5zrBoCv5Ijb6EF2Wx2UIRb5CcRDt4T4tomdhfL6iqneN+svkHzQr9rPHMtSfHsxZCsMolWjmv4FBaVQ88ZVrEcrY3IHqzREELr9LAtya4SjXq/qSAJSn0tN3yQpYqAp80zf9ORXI8S97DcVeL3EDnm66Hqb2NfkqQsIBUfDjPc9a/BoBaTl9Qykp1Bv2AQowb6SbyYqzyxgVHAyDG+s/1YoB4S1HhhkCN/6QfbnGWIt4rbACPvaigZjZ6ak4K5XcaftZSw4m34c0PRgxb0f1Vdh7a3LYfV+h2X9p93sPy3aMaUc3MetX8PAXntUZTDpcF3VVAnE9wictmp0AugyDlKn8vuigW7HEfEMyQiP3gI/aN4zTqfQhg2KSUODHgfk/cIe6211IHfq1Pg8rsmFJAHve9Omk+vef/zwg1+FyUtPHbqNt4z2IxEgQO0VMyxcfMgXpD3yOe+TU/sADSQMiWAW9GMyYF63bT/YJDSb2LX13IWBjwemPQfUGbs6ILEa2MoeGCFfNwR7wM+uO4cuwQldUE4X9k8ba5wFNE6oIuVECc3n4as5K/E+l9ifBD2Pqu28UFSf8T4teZVW1tY10mQ1FCLCclKNm/WXgLxiEu/+S0b+etSe4n6TeHXZNNQ/yXRcHGJfvLCKqWlVtCrHq/LRZt3
  template:
    metadata:
      name: cloudflare-api-token
      namespace: external-dns
    type: Opaque
