# Loki application configuration
app:
  name: loki
  namespace: monitoring
  cluster: mgmt
  project: mgmt-platform

  source:
    path: argocd/applications/mgmt/loki/charts
    helm:
      releaseName: loki
      valueFiles:
        - ../config/values.yaml

  destination:
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m

