apiVersion: v2
name: kube-prometheus-stack
description: Helm chart wrapper for kube-prometheus-stack via ArgoCD
version: 0.1.0
dependencies:
  - name: kube-prometheus-stack
    version: "67.7.0"
    repository: "https://prometheus-community.github.io/helm-charts"
