apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd
spec:
  project: mgmt-platform

  sources:
    # Helm chart source
    - repoURL: https://mojo2600.github.io/pihole-kubernetes
      chart: pihole
      targetRevision: 2.26.1
      helm:
        valueFiles:
          - $values/argocd/applications/mgmt/services/pihole/values.yaml

    # Values repo (this is what $values points to)
    - repoURL: git@github.com:IronPhysique/k8-devops.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: pihole

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
