apiVersion: v2
name: trivy-operator
description: Helm chart wrapper for Trivy Operator via ArgoCD
version: 0.1.0
dependencies:
  - name: trivy-operator
    version: "0.31.0"
    repository: "https://aquasecurity.github.io/helm-charts/"
