# Pihole application configuration
app:
  name: pihole
  namespace: pihole
  cluster: mgmt
  project: mgmt-platform

  source:
    path: argocd/applications/mgmt/pihole/charts
    helm:
      releaseName: pihole
      valueFiles:
        - ../config/values.yaml

  destination:
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m

