---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCukBuIW9bAeAyaIooi3Csgcdjs9sd8jj7V+9icOnHDr1k5074+CcekujdCg1oxtQ645TAdiV0PH6OVBw/CQ1UhIwFTyxhJ1tNnAku0S+g6MBqtApr7CF1aI2RdcxZQR5QhFf2sxbVg+qCmsfYrrkbm3HqAfHvFRJEgN21u8taLfdY3oJ/3SxdCC0tT90cxP7DPQvH9LNYQaYZ/u7ZpkD8jlyeq64BrFp4NP2WZEScFund0jBaVWPZtWK394ycPKL1PZugWX6TqbqFvurYGhHxGyFYjhVx4yP/1jinCIrqY1MFrmARw2exwawYvDJTvvEmIO1h1bDnFfWU6oMcLjbXC0ki8k2hQtBDCagnmLriZ0fXzhzefjwagYMHYZzECxtvC5qew01AUlwhSo/qTI8J+9mdiKmvgZ6uv30MoA5W7iwjxgMflkUq56HENOa2daml/9pPjU7lu9xgJdx+/+me0wJYm92kkIq1avdXbIapArMz7YH3NpooKELBVTn0k1YOYU20A/rDn+Q9VT9hsiPq4GpRBZEtvevrWRQcPfNIQCbsNwVgPQSpuA2vJ3UF8LnZY907SVpuqJ8o4sGy90fEXQAxW6/GGM2VWcX+iqKF/pp036ITziYx5iqUHMp/D/YiM7ZWn7d5qCDoMmlOaoE2NV7OSTcgDFoYgaZmYeNCiloLIhvCiGvIgycf0SagBHtXIpZwUQbMzBHptQEAMf+hXabN2mLvIfbsXRuN8bGpgZq+GYh2eISvd
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
