apiVersion: apps/v1
kind: Deployment
metadata:
  name: amp
  namespace: amp
  labels:
    app: amp
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: amp
  template:
    metadata:
      labels:
        app: amp
    spec:
      containers:
      - name: amp
        image: mitchtalmadge/amp-dockerized:latest
        ports:
        - name: web
          containerPort: 8080
        - name: amp-core
          containerPort: 8081
        - name: game-start
          containerPort: 25565
        - name: game-end
          containerPort: 25575
        env:
        - name: TZ
          value: "UTC"
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: USERNAME
          value: "admin"
        - name: PASSWORD
          value: "CHANGEME_amp_admin_password"
        volumeMounts:
        - name: amp-data
          mountPath: /home/amp
        resources:
          requests:
            cpu: 500m
            memory: 2Gi
          limits:
            cpu: 4000m
            memory: 8Gi
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
      volumes:
      - name: amp-data
        persistentVolumeClaim:
          claimName: amp-data
