---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCSJZihHonCwukrphLgcAkwmoZxQTfaFkQbVQEZ7HiQTvrDgV7vcTI2DzY0HHyTPPFSdFQSObm+y/zuhwAw99wJUSYzVyPF/3RBsI3gPhAZmaGSzMK/UcoobdbD5bH2eNOMXsMiTbkDvyiPoFI9OmEzJy0N7BP0ZTZC3OUtUDI4nPPql5kszIuCK5Q/p1W2gob3KTduQaaHpt3h678FscMsqneGFzUntA46uXsWBsVeDCAxwf0JrhPh61xPJymuv2wMQt6/+RVHWPzfUYFPJrM/H4wqrnDRSz1vRcCLQSu8AVHqx3dOtOe9bF3P6vyffVFXiAHP2d68IZnvhj3OKKVvkh6wK/Y7Kh1X0ytnVNowg8DoT+ETD+Swo28vfTiNJyRO+BQK/ZFbd2cFEp/FhWAuP2HRqhZNpKMPBEingQmLq39R7qSFqhsi4V/a5FERtn6NndMfVx456/3UVHs5vOg+2CCoZkWUgjufNssuc9LFQq6tcDkSqPoppbhQLh1qFJZdo2nBWAnEn25RgbtdDPSUlqvRpCxRnhH8BK/M6yl/MwCUypfiHW++Qxj23TH6FmNhA5teszRD+sXa4SILa7dr/dRzRw8w2BCdfQQD2mhjbq6Y9QWWuUT9HA9UlHPrA+5RQ4Gs9HS4S0hfv/xaqeL68/NBDb35DbbuPxGMi4CiHVE1IX2N1CLmwp4O/K+Bax790VMcwxlE/7elZRui7yqI24GbDY3Iv+pVstyGPeZz3ezD+KIWq73V
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
