apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: mgmt-platform
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns
    chart: external-dns
    targetRevision: 1.15.0
    helm:
      values: |
        provider: cloudflare
        env:
          - name: CF_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: cloudflare-api-token
                key: api-token
        domainFilters:
          - iron-lab.org
        policy: sync
        txtOwnerId: homelab-mgmt-cluster
        sources:
          - ingress
          - crd
        publishInternalServices: true
        extraArgs:
          - --default-targets=192.168.178.144
        logLevel: info
        logFormat: text
        interval: 5m
        triggerLoopOnEvent: true
        resources:
          requests:
            cpu: 25m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
