---
# Cert Manager for apps cluster
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-cert-manager
  namespace: argocd
  labels:
    cluster: apps
    component: platform
spec:
  project: apps-platform
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.16.2
    helm:
      valueFiles:
        - '$values/argocd/applications/apps/platform/cert-manager/values.yaml'
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: v1.16.2
    - repoURL: git@github.com:IronPhysique/k8-devops.git
      targetRevision: main
      ref: values
  destination:
    server: https://192.168.178.139:6443
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m
