---
# Nginx reverse proxy for mgmt cluster
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mgmt-nginx-router
  namespace: argocd
  labels:
    cluster: mgmt
    component: platform
spec:
  project: mgmt-platform
  source:
    repoURL: git@github.com:IronPhysique/k8-devops.git
    path: argocd/apps/nginx-router/base
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-router
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m
